# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name:		task-sugar
Version:	0.101.0
Release:	3
Summary:	Sugar Platform
License:	GPL
Group:		Graphical desktop/Other
Url:		http://sugarlabs.org/

Requires:	csound  
Requires:	csound-python  
Requires:	etoys >= 4.0.2340
Requires:	sugar-fructose >= 0.88.0
Requires:	sugar-glucose >= 0.88.0
Requires:	gstreamer1.0-plugins-base  
Requires:	gstreamer1.0-plugins-espeak
Requires:	gstreamer1.0-plugins-good  
Requires:	libxml2-python  
Requires:	python-numpy  
Requires:	pygame  

%description
The Sugar Platform is a set of versioned components on which activity
authors can rely when targeting their activities to run on a particular
Sugar version.
Installing Sugar Platform should mean for user that he can download actities
from http://activities.sugarlabs.org/ and they won't be failed due to
missed dependencies.

%files


