# NOTE: Do not edit, file was generated by jhconvert

Name: task-sugar
Version: 0.83.5
Release: %mkrel 1
Summary: Metapackage for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Requires: sugar-glucose
Suggests: sugar-fructose

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Metapackage for Sugar

%files
%defattr(-,root,root,-)

